## Responemos a la preguntas del análisis cuantitativo cerrado

In [15]:
import pandas as pd

# 1.
¿ Cuantos FTEs tiene la compañia en JULIO?
¿ que porcentaje de dedicación tiene los empleados durante el mes de Julio de 2019?

In [16]:
#abro archivo con cambios aplicados 
df_plantilla_julio = pd.read_csv("../files/processed/plantilla_julio_2019.csv")

C:\Users\sarag\AppData\Local\Temp\ipykernel_26568\1288667708.py:2: DtypeWarning: Columns (0: Área Funcional, 1: Nacionalidad) have mixed types. Specify dtype option on import or set low_memory=False.
  df_plantilla_julio = pd.read_csv("../files/processed/plantilla_julio_2019.csv")

In [17]:
# aunque la jornada en España es de 37.5 horas teóricas semanales  (código 156) y Brasil de 44 horas teoicas semanales (Código 185), 
# dado en la columna COD.UNIDAD DE NEGOCIO, COLUMNA Nº 6

In [18]:
#Calculamos la plantilla total de julio 
headcount_julio = len(df_plantilla_julio)

print (headcount_julio)

48431

In [19]:
df_plantilla_julio.columns

Index(['Convenio Aplicable', 'Localización País', 'Área Funcional',
       'Localización Ciudad', 'Año', 'COD. UNIDAD DE NEGOCIO', 'Mes',
       'Reducción de Jormada', 'División', 'Subactividad', 'Género',
       'Departamento', 'HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO',
       'Nombre del puesto', 'Nacionalidad',
       'PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES',
       'Fecha de Nacimiento', 'Clase de empleado', 'Discapacidad',
       'Fecha de Alta', 'ID persona'],
      dtype='str')

In [20]:

# Columnas clave
col_teoricas = "HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO"
col_trabajadas = "PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES"



# 2. FTEs por empleado (respetando la jornada de España 37.5h y Brasil 44h)
df_plantilla_julio["FTE"] = df_plantilla_julio[col_trabajadas] / df_plantilla_julio[col_teoricas]
total_ftes = df_plantilla_julio["FTE"].sum()

# 3. Porcentaje de dedicación
total_horas_trabajadas = df_plantilla_julio[col_trabajadas].sum()
total_horas_teoricas = df_plantilla_julio[col_teoricas].sum()
porcentaje_dedicacion = (total_horas_trabajadas / total_horas_teoricas) * 100

print(f"Headcount Julio 2019: {headcount_julio:,}".replace(",", "."))
print(f"Total FTEs: {total_ftes:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))
print(f"Porcentaje de dedicación: {porcentaje_dedicacion:.2f}%".replace(".", ","))

Headcount Julio 2019: 48.431
Total FTEs: 45.636,06
Porcentaje de dedicación: 93,96%

In [21]:
print (total_ftes)

45636.062303030296

# 2.
¿Cuantos empleados tiene la compañía a 31 de Agosto teniendo en cuenta las altas y las bajas de ese período?

In [22]:
#traigo archivos
df_bajas_agosto = pd.read_csv("../files/processed/bajas_agosto_2019.csv")
df_altas_agosto = pd.read_csv("../files/processed/altas_agosto_2019.csv")

In [23]:
# Cálculo del Headcount a 31 de Agosto
headcount_julio = len(df_plantilla_julio)
total_bajas = len(df_bajas_agosto)
total_altas = len(df_altas_agosto)

In [24]:
#formula 
headcount_agosto_31 = headcount_julio - total_bajas + total_altas

In [ ]:
print(f"• Plantilla inicio (Julio): {headcount_julio:,}".replace(",", "."))
print(f"• Bajas en Agosto: {total_bajas}")
print(f"• Altas en Agosto: {total_altas}")
print(f"• Headcount a 31 de Agosto: {headcount_agosto_31:,}".replace(",", "."))

• Plantilla inicio (Julio): 48.431
• Bajas en Agosto: 360
• Altas en Agosto: 583
• Headcount a 31 de Agosto: 48.654

# 3.
3. A. Índice de Rotación Bruta: Número de bajas totales / num empleados inicio del perído * 100

In [29]:
# estos datos ya los tenemo nº bajas totales = total_bajas
                           #nº empleados inios del periodo = headcount_julio.. que no es otra cosa que un lend.df_julio
indice_rotacion_bruta=( total_bajas/headcount_julio)*100
print( round(indice_rotacion_bruta,2))

0.74

3. B. Índice de Rotación Neta: [(Número de bajas + número de contrataciones) / 2] /num empleados inicio periodo * 100

In [31]:
indice_rotacion_neta = (((total_bajas + total_altas) / 2) / headcount_julio) * 100
print(round(indice_rotacion_neta, 2))

0.97

3. C. Índice de Rotación Bruta voluntaria: Número de bajas voluntarias / num empleados inicio del perído * 100

In [32]:
df_bajas_agosto.columns

Index(['ID persona', 'Unidad de Negocio', 'COD. UNIDAD DE NEGOCIO',
       'Subactividad_desc', 'Subactividad', 'Genero', 'Fecha nacimiento',
       'Fecha fin de contrato', 'Tipo de baja local', 'Tipo de baja global',
       'Nombre del puesto'],
      dtype='str')

In [ ]:
df_bajas_agosto['Tipo de baja local'].unique()

<StringArray>
[       'b.2) Otras bajas vegetativas',          'b.1) Renuncias voluntarias',
            'Dispensa Com Justa Causa', 'Dispensa sem Justa Causa AVP Inden.',
           'Falecimento morte natural',                     'Pedido Demissão',
           'Pedido Dem na Experiência',              'Antes Termino Contrato']
Length: 8, dtype: str

In [38]:
df_bajas_agosto[['Tipo de baja global','Tipo de baja local']]

,Tipo de baja global,Tipo de baja local
0,b.2) Otras bajas vegetativas,b.2) Otras bajas vegetativas
1,b.2) Otras bajas vegetativas,b.2) Otras bajas vegetativas
2,b.1) Renuncias voluntarias,b.1) Renuncias voluntarias
3,b.1) Renuncias voluntarias,b.1) Renuncias voluntarias
4,b.1) Renuncias voluntarias,b.1) Renuncias voluntarias
...,...,...
355,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
356,b.1) Renuncias voluntarias,Pedido Dem na Experiência
357,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
358,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
359,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.

In [39]:
df_bajas_agosto[['Tipo de baja global','Tipo de baja local']].sample(20)

,Tipo de baja global,Tipo de baja local
233,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
83,b.1) Renuncias voluntarias,Pedido Demissão
201,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
49,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
298,a.2 ) X otras causas (Indemnizaciones),Antes Termino Contrato
162,b.1) Renuncias voluntarias,Pedido Dem na Experiência
351,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
210,b.1) Renuncias voluntarias,Pedido Demissão
53,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
263,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
51,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
274,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
158,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
287,b.1) Renuncias voluntarias,Pedido Demissão
308,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
114,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
70,b.1) Renuncias voluntarias,Pedido Demissão
64,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
311,a.2 ) X otras causas (Indemnizaciones),Dispensa sem Justa Causa AVP Inden.
34,b.1) Renuncias voluntarias,Pedido Demissão

In [ ]:
#veo que mas o mnos es la mismo .. solo que baja local aparece tb en Portugues asi que el conteo lo hago con baja global

In [37]:
df_bajas_agosto['Tipo de baja global'].unique()

<StringArray>
[          'b.2) Otras bajas vegetativas',
             'b.1) Renuncias voluntarias',
 'a.2 ) X otras causas (Indemnizaciones)']
Length: 3, dtype: str

In [43]:
# Filtrar las bajas voluntarias
df_bajas_voluntarias = df_bajas_agosto[df_bajas_agosto['Tipo de baja global'].str.contains('Renuncias voluntarias', case=False, na=False)]

# Contar cuántas son
bajas_voluntaria = len(df_bajas_voluntarias)
print("Bajas voluntarias:", bajas_voluntaria)

Bajas voluntarias: 68

In [50]:
indice_rotacion_BRUTA_voluntaria=bajas_voluntaria/headcount_julio*100
print(f"El índice de rotación BRUTA de bajas VOLUNTARIAS es: {round(indice_rotacion_BRUTA_voluntaria, 2)}%")

El índice de rotación BRUTA de bajas VOLUNTARIAS es: 0.14%

3. D. Índice de Rotación Bruta Involuntaria: Número de bajas involuntarias / num empleados inicio del perído * 100

In [51]:
# bajas involuntarias = bajas totales (total_bajas_agosto)- bajas voluntaria (bajas_voluntarias)

In [60]:
df_bajas_agosto.head(1)

,ID persona,Unidad de Negocio,COD. UNIDAD DE NEGOCIO,Subactividad_desc,Subactividad,Genero,Fecha nacimiento,Fecha fin de contrato,Tipo de baja local,Tipo de baja global,Nombre del puesto
0,1716855,España,156,tecnologíayplanificación,Tecnología y Planificación,M,1952-02-12,2019-08-10,b.2) Otras bajas vegetativas,b.2) Otras bajas vegetativas,TITULADO SUPERIOR O MASTER

In [56]:
num_bajas_agosto=len(df_bajas_agosto)
print(num_bajas_agosto)

360

In [58]:
bajas_Involuntaria= num_bajas_agosto-bajas_voluntaria
print (f'El numero de bajas INVOLUNTARIAS es: {bajas_Involuntaria}')

El numero de bajas INVOLUNTARIAS es: 292

In [61]:
indice_rotacion_bruta_INVOLUNTARIA= (bajas_Involuntaria/headcount_julio)*100
print(f"El índice de rotación bruta de bajas INVOLUNTARIAS es: {round(indice_rotacion_bruta_INVOLUNTARIA, 2)}%")

El índice de rotación bruta de bajas INVOLUNTARIAS es: 0.6%

# 4.
4. Calcula la antigüedad media de los empleados que trabajan en Andalucía

In [62]:
df_plantilla_julio.columns

Index(['Convenio Aplicable', 'Localización País', 'Área Funcional',
       'Localización Ciudad', 'Año', 'COD. UNIDAD DE NEGOCIO', 'Mes',
       'Reducción de Jormada', 'División', 'Subactividad', 'Género',
       'Departamento', 'HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO',
       'Nombre del puesto', 'Nacionalidad',
       'PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES',
       'Fecha de Nacimiento', 'Clase de empleado', 'Discapacidad',
       'Fecha de Alta', 'ID persona', 'FTE'],
      dtype='str')

In [64]:
df_plantilla_julio['Localización Ciudad'].unique()

<StringArray>
[      'VIZCAYA',      'ALICANTE',     'TARRAGONA',        'HUESCA',
        'MADRID',      'ASTURIAS',       'GRANADA',    'PONTEVEDRA',
        'LLEIDA',       'SEVILLA',
 ...
  'PONTA GROSSA',       'MARINGA',      'CASCAVEL', 'FOZ DO IGUACU',
         'BELEM',      'Redencao',        'Macapá',        'Manaus',
      'São Luis',        'Itajaí']
Length: 290, dtype: str

In [69]:
# Con esto saco los trabajadores que son de Andalucia , los meto en una funcion

# 1. Lista de ciudades de Andalucía para filtrarlo por Andalucia
ciudades_andalucia = ['SEVILLA', 'MALAGA', 'GRANADA', 'CADIZ', 'HUELVA', 'ALMERIA', 'JAEN', 'CORDOBA']

# 2. Filtrar el DataFrame para quedarnos solo con Andalucía
df_andalucia = df_plantilla_julio[df_plantilla_julio['Localización Ciudad'].str.upper().isin(ciudades_andalucia)].copy()

In [70]:
# 3. Calcular la antigüedad en años
df_andalucia['Fecha de Alta'] = pd.to_datetime(df_andalucia['Fecha de Alta'])
fecha_referencia = pd.to_datetime('2019-07-31')

# Antigüedad en días dividida entre 365.25 para tener en cuenta los años bisiestos
df_andalucia['Antiguedad_anios'] = (fecha_referencia - df_andalucia['Fecha de Alta']).dt.days / 365.25

# 4. Antigüedad media
antiguedad_media = df_andalucia['Antiguedad_anios'].mean()

print(f"Empleados en Andalucía: {len(df_andalucia)}")
print(f"Antigüedad media en Andalucía: {antiguedad_media:.2f} años".replace(".", ","))

Empleados en Andalucía: 2032
Antigüedad media en Andalucía: 27,02 años