In [3]:
# importaciones

import pandas as pd
import numpy as np

import sys
import os

In [4]:
archivo = 'files/raw/datos_limpios.xlsx'
#cargamos cada dato por separado
df_julio = pd.read_excel(archivo, sheet_name='Plantilla a Julio 2019')
df_bajas = pd.read_excel(archivo, sheet_name='Bajas de Agosto 2019')
df_altas = pd.read_excel(archivo, sheet_name='Altas de Agosto 2019')

 # Cambios en el Data df_ julio :

 1) Tipo de contrato                                  
    solo hay un tipo fijo     
    no aporta nada pq solo hay un tipo se puede eliminar esta columna

In [5]:
df_julio['Tipo de contrato'].unique()

<StringArray>
['Fijo']
Length: 1, dtype: str

In [6]:
df_julio.columns

Index(['Convenio Aplicable', 'Localización País', 'Área Funcional',
       'Localización Ciudad', 'Subactividad_desc', 'Año',
       'COD. UNIDAD DE NEGOCIO', 'Mes', 'Reducción de Jormada',
       'Tipo de contrato', 'División', 'Subactividad', 'Género',
       'Departamento', 'HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO',
       'Nombre del puesto', 'Nacionalidad', 'Estado de empleado',
       'PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES',
       'Fecha de Nacimiento', 'Clase de empleado', 'Discapacidad',
       'Fecha de Alta', 'ID persona'],
      dtype='str')

In [7]:
df_julio = df_julio.drop(columns=['Tipo de contrato'])

In [8]:
df_julio.columns # compruebo que esta eliminada

Index(['Convenio Aplicable', 'Localización País', 'Área Funcional',
       'Localización Ciudad', 'Subactividad_desc', 'Año',
       'COD. UNIDAD DE NEGOCIO', 'Mes', 'Reducción de Jormada', 'División',
       'Subactividad', 'Género', 'Departamento',
       'HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO', 'Nombre del puesto',
       'Nacionalidad', 'Estado de empleado',
       'PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES',
       'Fecha de Nacimiento', 'Clase de empleado', 'Discapacidad',
       'Fecha de Alta', 'ID persona'],
      dtype='str')

2) Localización Ciudad:                   
            - A la hora de verlo vemos que sao paula y varias ciudades mas estan escritas de varias formas, por lo que los datos no son fidedignos
            - Observamos estos hechos 
            - Renombramos nombre de las ciudades es minúsculas y sin acentos, eliminando asi este problema

In [9]:
df_julio['Localización Ciudad'].dropna().unique()

<StringArray>
[      'VIZCAYA',      'ALICANTE',     'TARRAGONA',        'HUESCA',
        'MADRID',      'ASTURIAS',       'GRANADA',    'PONTEVEDRA',
        'LLEIDA',       'SEVILLA',
 ...
  'PONTA GROSSA',       'MARINGA',      'CASCAVEL', 'FOZ DO IGUACU',
         'BELEM',      'Redencao',        'Macapá',        'Manaus',
      'São Luis',        'Itajaí']
Length: 290, dtype: str

In [10]:
ciudades_unicas = sorted(df_julio['Localización Ciudad'].dropna().unique())
print(ciudades_unicas)

['A CORUÑA', 'ALAGOINHAS', 'ALAVA', 'ALBACETE', 'ALICANTE', 'ALMERIA', 'APARECIDA DE GOIANIA', 'ARACAJU', 'ARACATUBA', 'ARARAQUARA', 'ASTURIAS', 'AVILA', 'Anápolis', 'Aparecida de Goiania', 'Aracaju', 'Aracajú', 'Araguaina', 'Araraquara', 'BADAJOZ', 'BALEARES', 'BALNEÁRIO CAMBORIU', 'BARCELONA', 'BARREIRAS', 'BAURU', 'BELEM', 'BENTO GONCALVES', 'BLUMENAU', 'BRASILIA', 'BURGOS', 'Barueri', 'Bauru', 'Belem', 'Belo Horizonte', 'Bento Gonçalves', 'Betim', 'Blumenau', 'Boa Vista', 'Brasilia', 'Brasília', 'CABO FRIO', 'CACERES', 'CACHOEIRINHA', 'CACHOEIRO DE ITAPEMIRIM', 'CADIZ', 'CAMACARI', 'CAMPINAS', 'CAMPOS GOYTACAZES', 'CANOAS', 'CANTABRIA', 'CARIACICA', 'CARUARU', 'CASCAVEL', 'CASTELLON', 'CAXIAS DO SUL', 'CHAPECO', 'CIUDAD REAL', 'COLATINA', 'CONTAGEM', 'CORDOBA', 'CRICIUMA', 'CUENCA', 'CURITIBA', 'Campina Grande', 'Campinas', 'Campo Grande', 'Campos dos Goytacazes', 'Canoas', 'Caruaru', 'Cascavel', 'Catalao', 'Caxias do Sul', 'Chapeco', 'Colatina', 'Conselheiro Lafaiete', 'Contagem', 'Criciuma', 'Cuiaba', 'Cuiabá', 'Curitiba', 'D. CENTRAL', 'DUQUE DE CAXIAS RJ', 'DUQUE DE CAXIAS\xa0', 'Divinopolis', 'Dourados', 'Embu das Artes', 'Erechim', 'FEIRA DE SANTANA', 'FLORIANOPOLIS', 'FORTALEZA', 'FOZ DO IGUACU', 'Florianópolis', 'Fortaleza', 'Foz do Iguaçu', 'Franca', 'GARANHUNS', 'GIRONA', 'GRANADA', 'GRAVATAI', 'GUADALAJARA', 'GUARULHOS', 'GUIPUZCOA', 'Goiania', 'Goiânia', 'Governador Valadares', 'Guaiba', 'Guarapari', 'Guarapuava', 'Guaruja', 'Guarulhos', 'Gurupi', 'HUELVA', 'HUESCA', 'ILHEUS', 'ITABUNA', 'ITAJAI', 'Imperatriz', 'Indaiatuba', 'Ipatinga', 'Itajai', 'Itajaí', 'JAEN', 'JARAGUA DO SUL', 'JAU', 'JOINVILLE', 'JUNDIAI', 'Jaboatão dos Guararapes', 'Joao Pessoa', 'Joinville', 'Juazeiro do Norte', 'Juiz de Fora', 'Jundiaí', 'LA RIOJA', 'LAGES', 'LAS PALMAS', 'LEON', 'LINHARES', 'LLEIDA', 'LONDRINA', 'LUGO', 'Lages', 'Linhares', 'Londrina', 'MADRID', 'MALAGA', 'MANAUS', 'MARILIA', 'MARINGA', 'MAUA', 'MOGI DAS CRUZES', 'MURCIA', 'Macae', 'Macapa', 'Macapá', 'Maceio', 'Maceió', 'Manaus', 'Maraba', 'Maringa', 'Maringá', 'Marília', 'Mauá', 'Mogi das Cruzes', 'Montes Claros', 'Mossoró', 'NATAL', 'NAVARRA', 'NITEROI', 'NOVA IGUACU', 'NOVA SANTA RITA', 'NOVA VENECIA', 'NOVO HAMBURGO', 'Natal', 'Nilopolis', 'Niterói', 'Nova Iguaçu', 'Novo Hamburgo', 'OSASCO', 'OURENSE', 'Osasco', 'Ourinhos', 'PALENCIA', 'PALMAS', 'PASSO FUNDO', 'PETROLINA', 'PIRACICABA', 'PONTA GROSSA', 'PONTEVEDRA', 'PORTO ALEGRE', 'PORTO SEGURO', 'PRAIA GRANDE', 'PRESIDENTE PRUDENTE', 'Palmas', 'Paranaguá', 'Parnamirim', 'Passo Fundo', 'Passos', 'Patos de Minas', 'Pelotas', 'Pinhais', 'Piracicaba', 'Pocos de Caldas', 'Ponta Grossa', 'Porto Alegre', 'Porto Velho', 'Pouso Alegre', 'Praia Grande', 'Presidente Prudente SP', 'RESENDE', 'RIBEIRAO PRETO', 'RIO BRANCO', 'RIO DE JANEIRO', 'Recife', 'Redencao', 'Ribeirão Preto', 'Rio Branco', 'Rio Verde', 'Rondonopolis', 'S J Campos', 'SALAMANCA', 'SALVADOR', 'SANTA CRUZ DO SUL', 'SANTA MARIA', 'SANTO ANDRE', 'SANTOS', 'SAO BERNARDO DO CAMPO', 'SAO CARLOS', 'SAO JOSE', 'SAO JOSE CAMPOS', 'SAO JOSE DO RIO PRETO', 'SAO JOSE DOS CAMPOS', 'SAO JOSE RIO PRETO', 'SAO PAULO', 'SAO VICENTE', 'SEGOVIA', 'SERRA', 'SEVILLA', 'SORIA', 'SUZANO', 'Salvador', 'Santa Cruz do Sul', 'Santa Maria', 'Santana do Parnaíba', 'Santarem', 'Santo André', 'Santo Angelo', 'Santos', 'Sao Jose', 'Sao Jose do Rio Preto', 'Sao Jose dos Campos', 'Sao Luis', 'Sao Paulo', 'Sete Lagoas', 'Sinop', 'Sorocaba', 'SÃO CAETANO DO SUL', 'SÃO JOSÉ', 'SÃO MATEUS', 'SÃO PAULO', 'São Bernardo do Campo', 'São Gonçalo', 'São Jose dos Pinhais', 'São José', 'São Luis', 'São Paulo', 'TARRAGONA', 'TAUBATE', 'TEIXEIRA DE FREITAS', 'TENERIFE', 'TERUEL', 'TOLEDO', 'TUBARAO', 'Taboao da Serra', 'Tangara da Serra', 'Taubate', 'Teresina', 'Tubarão', 'UMUARAMA', 'Uberlandia', 'Uruguaiana', 'VALENCIA', 'VALLADOLID', 'VILA VELHA', 'VITORIA', 'VITORIA DA CONQUISTA', 'VIZCAYA', 'VOLTA REDONDA', 'Varginha', 'Votorantim', 'ZAMORA', 'ZARAGOZA']

In [11]:
from scr.funciones_analisis import limpiar_ciudades

In [12]:
limpiar_ciudades(df_julio, 'Localización Ciudad').head(10) #comprobamos que toda la ciudades estan en minusculas y sin acento lo que hace que no haya ciudades duplicadas por acentos

¡Columna 'Localización Ciudad' normalizada a minúsculas y sin tildes con éxito!

,Convenio Aplicable,Localización País,Área Funcional,Localización Ciudad,Subactividad_desc,Año,COD. UNIDAD DE NEGOCIO,Mes,Reducción de Jormada,División,...,HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO,Nombre del puesto,Nacionalidad,Estado de empleado,PROMEDIO DE HORAS SEMANALES TRABAJADAS EN EL MES,Fecha de Nacimiento,Clase de empleado,Discapacidad,Fecha de Alta,ID persona
0,Sí,España,Red - Planificación Tecnológica,vizcaya,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,ENCARGADO DE OPERACION,ESPAÑOLA,Activo,37.5,1954-09-08,EMP,No,1978-12-21,Persona 1716852
1,Sí,España,Red - Planificación Tecnológica,alicante,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,TITULADO SUPERIOR O MASTER,ESPAÑOLA,Activo,37.5,1952-02-12,EMP,No,1979-07-13,Persona 1716853
2,No,España,Direccion,tarragona,gestionydireccion,2019,156,Jul,No,CONSEJERA DELEGADA COO,...,37.5,TITULADO SUPERIOR O MASTER,ESPAÑOLA,Activo,37.5,1954-06-07,EMP,No,1981-12-01,Persona 1716854
3,Sí,España,Red - Planificación Tecnológica,huesca,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,OPERADOR DE COMUNICACIONES,ESPAÑOLA,Activo,37.5,1956-06-04,EMP,No,1981-12-01,Persona 1716855
4,Sí,España,Direccion,madrid,gestionydireccion,2019,156,Jul,No,ESTRATEGIA,...,37.5,TITULADO SUPERIOR O MASTER,ESPAÑOLA,Activo,37.5,1966-12-01,EMP,No,1986-12-15,Persona 1716856
5,Sí,España,Red - Planificación Tecnológica,madrid,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,OPERADOR DE COMUNICACIONES,ESPAÑOLA,Activo,37.5,1968-02-25,EMP,No,1988-11-21,Persona 1716857
6,Sí,España,Red - Planificación Tecnológica,asturias,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,ENCARGADO DE OPERACION,ESPAÑOLA,Activo,37.5,1968-11-10,EMP,No,1989-06-30,Persona 1716858
7,Sí,España,Red - Planificación Tecnológica,granada,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,OPERADOR DE COMUNICACIONES,ESPAÑOLA,Activo,37.5,1968-05-06,EMP,No,1990-05-21,Persona 1716859
8,Sí,España,Red - Planificación Tecnológica,pontevedra,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,OPERADOR DE COMUNICACIONES,ESPAÑOLA,Activo,37.5,1967-01-19,EMP,No,1990-09-10,Persona 1716860
9,Sí,España,Red - Planificación Tecnológica,madrid,tecnologíayplanificación,2019,156,Jul,No,"OPERACIONES, RED Y TI",...,37.5,TITULADO/TECNICO MEDIO O DE GRADO,ESPAÑOLA,Activo,37.5,1972-03-21,EMP,No,1991-07-08,Persona 1716861

3)   Subactividad:  
    da exactamente lo mismo que subactividad_des, columna copiada eliminar una de las 2

In [13]:
df_julio.columns

Index(['Convenio Aplicable', 'Localización País', 'Área Funcional',
       'Localización Ciudad', 'Subactividad_desc', 'Año',
       'COD. UNIDAD DE NEGOCIO', 'Mes', 'Reducción de Jormada', 'División',
       'Subactividad', 'Género', 'Departamento',
       'HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO', 'Nombre del puesto',
       'Nacionalidad', 'Estado de empleado',
       'PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES',
       'Fecha de Nacimiento', 'Clase de empleado', 'Discapacidad',
       'Fecha de Alta', 'ID persona'],
      dtype='str')

In [14]:
son_iguales= (df_julio['Subactividad_desc']== df_julio['Subactividad']).all()
print (son_iguales)

False

In [15]:
df_julio[['Subactividad_desc','Subactividad']] # demuestro que son iguales y como veo que subactivad_desc esta peor escrita es la columna que quito

,Subactividad_desc,Subactividad
0,tecnologíayplanificación,Tecnología y Planificación
1,tecnologíayplanificación,Tecnología y Planificación
2,gestionydireccion,Gestión y Direccion
3,tecnologíayplanificación,Tecnología y Planificación
4,gestionydireccion,Gestión y Direccion
...,...,...
48426,producciónit,Producción IT
48427,aplicaciones/desarrollo,Aplicaciones/Desarrollo
48428,canaltelefónico-atención,Canal telefónico - Atención
48429,soporteventas,Soporte ventas
48430,desarrollodeproyectosestratégicosytransformación,Desarrollo de Proyectos Estratégicos y Transfo...

In [16]:
df_julio = df_julio.drop(columns=['Subactividad_desc'])

In [17]:
df_julio.columns#compruebo que esta bien hecho

Index(['Convenio Aplicable', 'Localización País', 'Área Funcional',
       'Localización Ciudad', 'Año', 'COD. UNIDAD DE NEGOCIO', 'Mes',
       'Reducción de Jormada', 'División', 'Subactividad', 'Género',
       'Departamento', 'HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO',
       'Nombre del puesto', 'Nacionalidad', 'Estado de empleado',
       'PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES',
       'Fecha de Nacimiento', 'Clase de empleado', 'Discapacidad',
       'Fecha de Alta', 'ID persona'],
      dtype='str')

4) Estado de empleado                                   
    solo hay 1 activo  no tiene sentido, eliminar columna

In [18]:
df_julio['Estado de empleado'].unique()

<StringArray>
['Activo']
Length: 1, dtype: str

In [19]:
df_julio = df_julio.drop(columns=['Estado de empleado'])

In [20]:
df_julio.columns # comprobacion

Index(['Convenio Aplicable', 'Localización País', 'Área Funcional',
       'Localización Ciudad', 'Año', 'COD. UNIDAD DE NEGOCIO', 'Mes',
       'Reducción de Jormada', 'División', 'Subactividad', 'Género',
       'Departamento', 'HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO',
       'Nombre del puesto', 'Nacionalidad',
       'PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES',
       'Fecha de Nacimiento', 'Clase de empleado', 'Discapacidad',
       'Fecha de Alta', 'ID persona'],
      dtype='str')

5) ID persona   
        pone `persona y numero  ---- Persona 1716852 eliminar la palabra persona y espacio dejar solo el numero

In [21]:
from scr.funciones_analisis import limpiar_id_persona

In [22]:
df_julio = limpiar_id_persona(df_julio, 'ID persona')

In [23]:
df_julio['ID persona'].head()

0    1716852
1    1716853
2    1716854
3    1716855
4    1716856
Name: ID persona, dtype: str

 # Cambios en el Data df_bajas :

1) ID persona   
        pone persona y numero  ---- Persona 1716852 eliminar la palabra persona y espacio dejar solo el numero

In [24]:
from scr.funciones_analisis import limpiar_id_persona
df_bajas= limpiar_id_persona(df_bajas,'ID persona')
df_bajas['ID persona'].head()

0    1716855
1    1716863
2    1716872
3    1716873
4    1716956
Name: ID persona, dtype: str

2)  Clase de empleado         
                    solo hay una clase EMP, no tiene sentido mantener la columna
                    eliminar columna

In [25]:
df_bajas=df_bajas.drop(columns=['Clase de empleado'])

In [26]:
df_bajas.columns

Index(['ID persona', 'Unidad de Negocio', 'COD. UNIDAD DE NEGOCIO',
       'Subactividad_desc', 'Subactividad', 'Genero', 'Fecha nacimiento',
       'Fecha fin de contrato', 'Tipo de baja local', 'Tipo de baja global',
       'Nombre del puesto'],
      dtype='str')

 # Cambios en el Data df_altas :

1) ID persona   
        pone persona y numero  ---- Persona 1716852 eliminar la palabra persona y espacio dejar solo el numero

In [27]:
from scr.funciones_analisis import limpiar_id_persona
df_altas= limpiar_id_persona(df_altas,'ID Persona')
df_altas['ID Persona'].head()

0    19887
1    19888
2    19890
3    19891
4    19892
Name: ID Persona, dtype: str

2)  Clase de empleado         
                    solo hay una clase EMP, no tiene sentido mantener la columna
                    eliminar columna

In [28]:
df_altas.columns

Index(['Subactividad_desc', 'Subactividad', 'Genero', 'Fecha nacimiento',
       'Clase empleado', 'Nombre del puesto', 'COD. UNIDAD DE NEGOCIO',
       'Fecha alta', 'Tipo alta local', 'Tipo alta global', 'ID Persona'],
      dtype='str')

In [29]:
#df_altas=df_altas.drop(columns=['Clase empleado'])

3)   'Tipo alta local' y 'Tipo alta global'
    da exactamente lo mismo,
    columna copiada eliminar una de las 2

In [30]:
df_altas.columns

Index(['Subactividad_desc', 'Subactividad', 'Genero', 'Fecha nacimiento',
       'Clase empleado', 'Nombre del puesto', 'COD. UNIDAD DE NEGOCIO',
       'Fecha alta', 'Tipo alta local', 'Tipo alta global', 'ID Persona'],
      dtype='str')

In [31]:
df_altas[['Tipo alta local', 'Tipo alta global']] # demuestro que son iguales y como veo que subactivad_desc esta peor escrita es la columna que quito

            Tipo alta local                            Tipo alta global
0    c.2) Reincorporaciones                      c.2) Reincorporaciones
1    c.2) Reincorporaciones                      c.2) Reincorporaciones
2    c.2) Reincorporaciones                      c.2) Reincorporaciones
3    c.2) Reincorporaciones                      c.2) Reincorporaciones
4    c.2) Reincorporaciones                      c.2) Reincorporaciones
..                      ...                                         ...
578                Admissão  a) Procedentes de empresas AJENAS AL GRUPO
579                Admissão  a) Procedentes de empresas AJENAS AL GRUPO
580                Admissão  a) Procedentes de empresas AJENAS AL GRUPO
581                Admissão  a) Procedentes de empresas AJENAS AL GRUPO
582                Admissão  a) Procedentes de empresas AJENAS AL GRUPO

[583 rows x 2 columns]

In [32]:
#parecia que si pero comprobanmos que no , asi que se quedan las 2 columnas

Guardado de documentos con los cambios aplicados

In [33]:
import os

# 1. Asegurarnos de que la carpeta existe (usando el nombre exacto de tu estructura)
os.makedirs("files/procesed", exist_ok=True)

# 2. Guardar cada DataFrame en formato CSV correctamente
df_julio.to_csv("files/procesed/plantilla_julio_2019.csv", index=False, encoding="utf-8")
df_bajas.to_csv("files/procesed/bajas_agosto_2019.csv", index=False, encoding="utf-8")
df_altas.to_csv("files/procesed/altas_agosto_2019.csv", index=False, encoding="utf-8")

print("¡Archivos guardados correctamente en files/procesed/!")

¡Archivos guardados correctamente en files/procesed/!